version: "3"
services:
  app:
    image: audriusbuk/violeta
    container_name: violeta
    build:
      context: .
      dockerfile: /docker/app/Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-tier
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: docker/violeta_node
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"